const PHOTO_FILENAME = /^[a-f0-9]{16}\.(?:jpg|png|webp)$/i;

/** Accept only filenames generated by the backend photo endpoints. */
export function photoFilename(path: string | null | undefined): string | null {
  if (typeof path !== "string" || !path) return null;
  const candidate = path.replaceAll("\\", "/").split("/").pop() || "";
  return PHOTO_FILENAME.test(candidate) ? candidate : null;
}

export function photoUrl(path: string | null | undefined): string | null {
  const filename = photoFilename(path);
  return filename ? `/uploads/${encodeURIComponent(filename)}` : null;
}
